-- phpMyAdmin SQL Dump
-- version 5.1.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 17, 2022 at 10:45 AM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 7.4.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `project`
--

-- --------------------------------------------------------

--
-- Table structure for table `concern`
--

CREATE TABLE `concern` (
  `id_concern` int(11) NOT NULL,
  `nama_concern` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `concern`
--

INSERT INTO `concern` (`id_concern`, `nama_concern`) VALUES
(1, 'Kulit Sensitif'),
(2, 'Komedo'),
(3, 'Aging'),
(4, 'Kulit Kusam'),
(5, 'Kantung Mata'),
(6, 'Pori Besar'),
(7, 'Skin Tightening'),
(8, 'Jerawat');

-- --------------------------------------------------------

--
-- Table structure for table `skincare`
--

CREATE TABLE `skincare` (
  `id_skincare` int(11) NOT NULL,
  `nama_skincare` varchar(50) NOT NULL,
  `deskripsi` text NOT NULL,
  `ingredient` text NOT NULL,
  `harga` int(6) NOT NULL,
  `rating` float NOT NULL,
  `gambar` varchar(225) NOT NULL,
  `id_concern` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `skincare`
--

INSERT INTO `skincare` (`id_skincare`, `nama_skincare`, `deskripsi`, `ingredient`, `harga`, `rating`, `gambar`, `id_concern`) VALUES
(1, 'STUDIO TROPIK – Prombiome Skin', 'Studio Tropik Probiome Skin Tonic memiliki formula creamy untuk menghidrasi dan memperbaiki kulit kering dan sensitif. Memberikan efek ‘plumping’ pada kulit yang sangat dehidrasi.\r\n\r\n\r\nAwali skincare routine dengan Skin Tonic: ‘welcome drink’ spesial untuk kulitmu. Diaplikasikan setelah mencuci muka untuk mengaktifkan ‘super sponge mode’ yang membuat kulit lebih lembut dan kenyal; siap untuk rangkaian skincare berikutnya! #CheersToBetterSkin\r\n', 'Active Ingredients:\r\nBifidaLacto Probiotics (Bifida ferment lysate + Lactobacillus)\r\nPGA (Polyglutamic Acid)\r\nQuadruple HA (Hyaluronic\r\n', 331890, 4.7, 'image\\1.png', 1),
(2, 'HALE – Exfoliatig Potion', 'Serum bertekstur gel ringan yang mengandung 6.3% Glycolic Acid (AHA) dan 2% Willow Bark Extract yang membantu meluruhkan sel kulit mati membuat tekstur kulit lebih halus, membantu mengurangi masalah pori tersumbat, dan mengurangi hiperpigmentasi. Dilengkapi dengan Allantoin yang efekftif menenangkan kulit.', 'Water, Glycolic Acid, Glycerin, Propanediol, Salix Alba (Willow) Bark Extract, Sodium Hydroxide, 1,2-Hexanediol, Pentylene Glycol, Calendula Officinalis Flower Extract, Xanthan Gum, Ethylhexylglycerin, Allantoin, Disodium EDTA, Salicylic Acid, Tocopherol', 119000, 4.3, 'image\\2.png', 2),
(3, 'MURAD – Vita-C Dark Circle Cor', 'Serum mata vitamin C yang distabilkan dengan emas melawan tampilan lingkaran hitam hanya dalam 2 minggu.\r\nKompleks Vita-C yang unik meningkatkan stabilitas dan potensi asam L-askorbat\r\nMineral mikro yang memantulkan cahaya langsung mencerahkan\r\n\r\nKulit tipis dan tembus pandang di sekitar mata lebih cenderung menunjukkan perubahan warna dan tanda-tanda penuaan. Vitamin C sangat penting untuk area yang sensitif karena memberikan pertahanan antioksidan yang ditingkatkan untuk kulit yang lebih cerah dan tampak lebih sehat. Diformulasikan untuk menargetkan beberapa jenis lingkaran hitam: Biru/ungu: Mikrosirkulasi rendah dan kulit tipis di sekitar mata meningkatkan visibilitas darah tidak teroksigenasi (yang berwarna biru). Coklat: Kerusakan akibat sinar matahari, iritasi dan genetika dapat menyebabkan hiperpigmentasi. Merah: Dipicu oleh peradangan, iritasi dan alergi.\r\n\r\n', 'Gold Stabillized Vit C, Red and Brown Algae Extracts, Light Reflecting Micro Minerals, Cucumber Extract', 1350000, 4, 'image\\3.png', 3),
(4, 'DEAR KLAIRS - Freshly Juiced V', 'Freshly Juice Vitamin Drop adalah antioksidan yang terbaik dalam mencegah penuaan dan membantu mencerahkan kulit wajah. Klairs Juiced Vitamin Drop mengandung 5% ascorbic acid cocok untuk semua jenis kulit dan usia bahkan jika anda memiliki kulit yang super sensitif.\r\nKlairs Juiced vitamin drop dapat membantu:\r\n1. Mencegah pertumbuhan pigmentasi baru yang disebabkan oleh sinar matahari.\r\n2. Mengecilkan pori-pori besar\r\n3. Mencerahkan dan mengencangkan kulit wajah\r\n4. Memudarkan bekas-bekas jerawat\r\n', 'Water, Propylen Glycol, Ascorbic Acid(5%, Hydroxyethylcellulose, Centella Asiatica Extract, Citrus Junos Fruit Extract, Illicium Verum(Anise) Fruit Extract, Citrus Paradisi(Grapefruit) Fruit Extract, Nelumbium Speciosum Flower Extract, Paeonia Suffruticosa Root Extract, Scutellaria Baicalensis Root Extract, Polysorbate 60, Brassica Oleracea Italica (Broccoli) Extract, Chaenomeles Sinensis Fruit Extract, Orange Oil Brazil, Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Disodium EDTA, Lavandula Angustifolia (Lavender) Oil, Camellia Sinensis Callus Culture Extract, Larix Europaea Wood Extract, Chrysanthellum Indicum Extract, Rheum Palmatum Root Extract, Asarum Sieboldi Root Extract, Quercus Mongolia Leaf Extract, Persicaria Hydropiper Extract, Corydalis Turtschaninovii Root Extract, Coptis Chinensis Root Extract, Magnolia Obovata Bark Extract, Lysine HCL, Proline, Sodium Ascorbyl Phosphate, Acetyl Methionine, Theanine, Lecithin, Acetyl Glutamine,SH-Olgopeptide-1, SH-Olgopeptide-2, SH-Polypeptide-1, SH-Polypeptide-9, SH-Polypeptide-11, Bacillus/Soybean/Folic Acid Ferment Extract, Sodium Hyaluronate, Caprylyl Glycol, Butylene Glycol, 1,2-Hexanediol', 324000, 4.3, 'image\\4.png', 4),
(5, 'HOLIKA HOLIKA – Honey Royalact', 'Mata lelah, kerutan dan kehilangan elastisitas merupakan 3 permasalahan disekitar mata. Dengan Intensive Triple Care™ pada krim mata membuat kulit mata lebih elastis, lembab dan cerah. Teruji secara dermatologis dan tidak mengiritasi kulit.\r\n\r\nIntensive Triple Care™\r\n1. Hydrolyzed kolagen : Meningkatkan kepadatan dari sel kulit dan elastisitas kulit dengan menstimulasi generasi kolagen kulit.\r\n2. Idebenone : Memberikan nutrisi untuk kulit dengan efek anti-oksidan yang unggul, 4 kali lebih lembab dari vitamin dan 10 kali lebih dari coenzyme Q10\r\n3. Peptide : 3 jenis peptide meningkatkan elastisitas kulit\r\n', 'Fermented Honey, Royalactin, Hydrolyzed kolagen, Idebenone, Peptide, Niacinamide', 350000, 3.8, 'image\\5.png', 5),
(6, 'COSRX – One Step Green Hero Ca', 'COSRX\'s One Step Green Hero Calming Pad merupakan set toner wajah yang memberikan sensasi menenangkan kulit sensitif. Diformulasikan dengan green tea dan witch hazel, toner yang lembut ini mampu menyamarkan pori-pori yang terlihat, menghidrasi kulit, mengurangi minyak berlebih dan mengurangi kemerahan pada kulit.', 'Camellia Sinensis Leaf Water, Butylene Glycol, Taraxacum Officinale (Dandelion) Leaf Extract, Centella Asiatica Extract, Hamamelis Virginiana (Witch Hazel) Leaf Extract, Melaleuca Alternifolia (Tea Tree) Leaf Extract, Artemisia Princeps Extract, 1,2-Hexanediol, Cassia Obtusifolia Seed Extract, Lactobionic Acid, Maltodextrin, Panthenol, Polyglyceryl-10 Laurate, Polyglyceryl-10 Myristate, Glycerine, Arginine, Allantoin, Asiaticoside, Asiatic Acid, Madecassic Acid, Sodium Hyaluronate, Gardenia Florida Fruit Extract, Citrus Aurantium Bergamia (Bergamot) Fruit Oil, Menthyl Lactact, Mentha Haplocalix Extract.', 224925, 4.5, 'image\\6.png', 6),
(7, 'BIODERMA – Serum Lotion', 'Lotion khusus untuk kulit kombinasi, berminyak, dan cenderung berjerawat yang membantu mengatur pH kulit dan mengurangi kadar minyak berlebih pada wajah. Lotion ini juga menghidrasi kulit sepanjang 8 jam dan mencegah kulit terlihat kusam karena dehidrasi. Bebas alergi, hipoalergenik, dan non-komedogenik.\r\n\r\nDetail produk dari Sebium Lotion: - Mengurangi kemungkinan pori-pori / jerawat tersumbat. - Patent FLUIDACTIV-nya mengurangi kadar minyak berlebih pada kulit. - Mencegah penebalan sebum dan pembentukan jerawat. - Memperkuat kulit dan membuatnya lebih tahan terhadap serangan luar. - Anti-oksidan dan anti-inflamasi. - Mengatur pH kulit ke tingkat yang sehat. - Menghidrasi sekaligus melembutkan kulit. - Memperbaiki tekstur kulit dan mengencangkan pori-pori pada wajah.\r\n', 'AQUA/WATER/EAU, PEG-11 METHYL ETHER DIMETHICONE, BUTYLENE GLYCOL, GLYCERIN, FOMES OFFICINALIS (MUSHROOM) EXTRACT, CAPRYLOYL GLYCINE, POLYSORBATE 20, SODIUM CITRATE, ZINC GLUCONATE, SALICYLIC ACID, SODIUM HYDROXIDE, MANNITOL, SODIUM METABISULFITE, XYLITOL, RHAMNOSE, PYRIDOXINE HCL, PROPYL GALLATE, PEG-40 HYDROGENATED CASTOR OIL, FRUCTOOLIGOSACCHARIDES, PHENOXYETHANOL, FRAGRANCE (PARFUM).', 250100, 4.3, 'image\\7.png', 7),
(8, 'BIO BEAUTY LAB – Acne Treatmen', 'ACNE TREATMENT FACE OIL dapat membantu penyembuhan jerawat & beruntusan meradang secara cepat, mengontrol kadar minyak berlebih pada wajah, memudarkan flek hitam dan bekas jerawat pada wajah. Bisa di mix juga dengan foundation atau di pakai sebagai base makeup', 'grapeseed oil, jojoba oil, squalane oil, tamanu seed oil, vitamin E , tea tree essential oil, rosemary essential oil, lavender essential oil.', 320000, 4.6, 'image\\8.png', 8),
(9, 'SKIN GAME – Acne Warrior Spot ', 'Obat totol jerawat yang membantu merawat kulit berjerawat', 'Aqua, Glycerin, Calamine, Bentonite, ZnO, Kaolin, Sulfur, Propylene Glycol, Polysorbate20, Salicylic Acid, Polyacrylamide, Phenoxyethanol, C13-14 Isoparaffin, C9-11 Pareth 6, Carboxymethyl Cellulose, Sodium Chloride', 125000, 4.6, 'image\\9.png', 8),
(10, 'SOME BY MI – Super atcha Pore ', '10 in 1 clay mask dengan perpaduan daun Teh Hijau dan bubuk Matcha untuk merawat pori-pori secara mudah dan praktis. Memiliki tekstur yang lembut dan creamy, membuat kulit terasa segar dan halus setelah diaplikasikan. Masker clay ini bekerja melalui 4 langkah:\r\n\r\n1. BHA, ekstrak White Willow, Teh Hjau: Membuka pori-pori yang tersumbat dengan mengangkat sel kulit mati\r\n2. Clay, bubuk Matcha: Membersihkan sebum, sel kulit mati, kotoran, dan komedo pada wajah\r\n3. Ekstrak Centella Asiatica, air Tea Tree, bubuk Houttuynia Cordata, ekstrak Daun Chamaeccyparis Obtusa, Glacial Water, Sparkling Water: Memberikan kelembapan secara intens ke dalam pori-pori\r\n4. Air Matcha, Clay: Mengencangkan pori-pori\r\n', 'Water, Kaolin(120,000 ppm), Glycerin, Camellia Sinensis Leaf Water(102,000 ppm), Titanium Dioxide(CI 77891), Bentonite, Magnesium Aluminum Silicate, Chamaecyparis Obtusa Leaf Extract, Silica, Manicouagan Clay(1,000 ppm), Camellia Sinensis Leaf(50 ppm), Camellia Sinensis Leaf Powder(4,000 ppm), Houttuynia Cordata Powder, Centella Asiatica Extract, Camellia Sinensis Leaf Extract(100 ppm), Salix Alba (Willow) Bark Extract, Rosa Rugosa Leaf Extract, Melissa Officinalis Leaf Extract, Water(Glacier Water), Melaleuca Alternifolia (Tea Tree) Leaf Water, Water(Carbonated Water), Allantoin, Madecassic Acid, Asiaticoside, Asiatic Acid, Capryloyl Salicylic Acid, Butylene Glycol, Caprylyl Glycol, Xanthan Gum, Polyvinyl Alcohol, 1,2-Hexanediol, Benzyl Glycol, Ethylhexylglycerin, Raspberry Ketone, Fragrance', 194000, 4.6, 'image\\10.png', 1),
(11, 'PUREHEALS – Propolis Softening', 'Peeling toner yang membersihkan kulit dan mengangkat sel kulit mati dengan lembut tanpa menyebabkan iritasi agar kulit menjadi halus dan cerah bercahaya. Toner ini mengandung ekstrak propolis, 13 jenis essential oil dan asam laktat melembabkan, membantu melindungi kulit, menyeimbangkan kadar minyak berlebih, dan menenangkan kulit.', 'Water, Butylene Glycol, Niacinamide, Betaine, Propolis Extract, Sodium Hydroxide, PEG-40 Hydrogenated Castor Oil, Caprylyl Glycol, 1,2-Hexanediol, Glycerin, Salicylic Acid, Aloe Barbadensis Leaf Extract, Lactic Acid, Illicium Verum (Anise) Fruit Extract, Adenosine, Tocopheryl Acetate, Carbomer, Benzyl Alcohol, Citrus Limon (Lemon) Peel Oil, Citrus Aurantium Dulcis (Orange) Peel Oil, Pelagornium Graveolens Flower Oil, Lavandula Angustifolia (Lavender) Oil, Melaleuca Alternifolia (Tea Tree) Leaf Oil, Vetiveria Zizanoides Root Oil, Cymbopogon Schoenanthus Oil, Dehydroacetic Acid, Eugenia Caryophyllus (Clove) Leaf Oil, Acetic Acid, Mentha Arvensis Leaf Oil, Rose Flower Oil, Tagetes Minuta Flower Oil, Elettaria Cardamomum Seed Oil, Thymus Vulgaris (Thyme) Oil', 219200, 4.4, 'image\\11.png', 2),
(12, 'MOMOPURI – Face Lotion', 'Toner dengan tekstur cair dan diformulasikan dengan Peach Ceramide dan Lactobacillus Paste, berfungsi untuk:\r\n- Memperkuat lapisan pelindung kulit\r\n- Meningkatkan regenerasi dan elastisitas kulit\r\n- Menghidrasi dan mencerahkan kulit\r\n- Mengencangkan pori-pori\r\n- Membuat kulit tetap lembut dan lembap\r\n\r\nDapat memberikan hidrasi yang tahan lama pada kulit sampai ke bagian dalam, sehingga kulit terasa kencang dan kenyal. Mempunyai aroma Peach yang segar dan cocok digunakan pada kulit normal cenderung berminyak\r\n', 'WATER (AQUA), DIPROPYLENE GLYCOL, GLYCERIN, PEG/PPG/POLYBUTYLENE GLYCOL-8/5/3 GLYCERIN, ARGININE, ENTEROCOCCUS FAECALIS, ZEA MAYS (CORN) OIL (ZEA MAYS), ASCORBYL TETRAISOPALMITATE, TOCOPHEROL, RETINYL PALMITATE, SODIUM HYALURONATE, PHYTOSTERYL GLUCOSIDE/GLUCOSYLCERAMIDE, CITRUS AURANTIUM BERGAMIA (BERGAMOT) FRUIT EXTRACT, METHYL GLUCETH-20, PRUNUS PERSICA (PEACH) LEAF EXTRACT (PRUNUS PERSICA), SILVER OXIDE, BUTYLENE GLYCOL, GLYCERETH-25 PCA ISOSTEARATE, SODIUM OLEATE, XANTHAN GUM, XYLITOL, CITRIC ACID, SODIUM CITRATE, PHYTIC ACID, POLYGLYCERYL-5 LAURATE, FRAGRANCE (PARFUM)', 165750, 4.7, 'image\\12.png', 3),
(13, 'LOREAL PARIS – Revitalift 1.5%', 'Serum wajah dengan konsentrasi Hyaluronic Acid tertinggi** dengan 2 jenis HA dalam satu formula. +42% kulit cerah seketika.\r\n\r\nL\'Oréal Paris® Revitalift 1.5%  Hyaluronic Acid Serum mengandung Macro Hyaluronic Acid yang berfungsi melembapkan wajah secara intens untuk kulit terasa halus dan juga Micro Hyaluronic Acid yang menyerap ke dalam kulit untuk melembapkan kulit dari dalam. Kulit lembap dan halus seketika lebih cerah dengan serum wajah L’Oreal Paris 1,5% mengacu pada persentase total Hyaluronic Acid dan turunannya yang ditambahkan ke formula produk ini *Konsentrasi Hyaluronic Acid tertinggi pada produk revitalift. L\'Oreal Paris\r\n', 'Revitalift 1.5% Hyaluronic Acid Serum telah dikembangkan secara khusus untuk memberikan hasil kulit muda dan tampak bercahaya di wajah yang canggih dengan proses penyerapan serum yang cepat dan hasil akhir yang tidak berminyak. Campuran 2 bentuk Asam Hyaluronic murni yang diformulasikan secara ilmiah, untuk membantu mempertahankan kelembaban kulit: 0,5% Macro Hyaluronic Acid untuk wajah berguna rehidrasi dan menghaluskan permukaan kulit secara intensif dengan mempertahankan 1000x beratnya dalam air dan 1% dari Asam Hyaluronic Mikro untuk menembus ke lapisan kulit untuk membantu meningkatkan kelembapan alami wajah sehingga wajah tampak muda bercahaya.', 209920, 4.6, 'image\\13.png', 4),
(14, 'KEANA NADESHIKO – Rice Mask', '‘Keana Nadeshiko rice skincare’ mengandung 100% Japanese rice-derived skincare serum yang membuat kulit kering menjadi lembut dan lembap, terbuat dari 100% beras buatan Jepang.\r\n\r\nRice mask isi 10pcs dengan lembaran masker yang tebal diperkaya beauty essence yang melekat dengan baik pada kulit. Berfungsi untuk menghasilkan tekstur kulit yang lembut, lembap, dan kenyal.\r\n\r\nDirekomendasikan untuk kulit kering dengan pori-pori yang besar, menonjol, dan terlihat jelas.\r\n', 'Water, Glycerin, Propylene Glycol, Alcohol, Styrene/VP Copolymer, Xanthan Gum, Phenoxyethanol, Methylparaben, Butylene Glycol, Rice Ferment Filtrate (Sake), Oryza Sativa (Rice) Bran Oil, Glycosphingolipids, Hydrogenated Lecithin, Hydrogenated Lysolecithin, Pentylene Glycol, Arginine, Polysorbate 80, Sodium Citrate, Citric Acid, Hydrolized Rice Bran Extract', 99900, 4.8, 'image\\14.png', 4),
(15, 'BREYLEE – Pomegranate Mask', 'Eye mask Dengan bahan lembut yang pas diletakan pada bagian bawah area mata untuk melembabkan, mencerahkan serta mengencangkan area tersebut.', 'AQUA, GLYCERIN, SORBITOL, BUTYLENE GLYCOL, AVENA SATIVA BRAN EXTRACT, CENTELLA ASIATICA EXTRACT, ARBUTIN, BIFIDA FERMENT LYSATE, CHONDRUS CRISPUS EXTRACT, LEONTOPODIUM ALPINUM FLOWER/LEAF EXTRACT, PENTYLENE GLYCOL, 1,2-HEXANEDIOL, POTASSIUM CHLORIDE, PUNICA GRANATUM FRUIT EXTRACT, CLADOSIPHON OKAMURANUS EXTRACT, BETA-GLUCAN, XANTHAN GUM, CALCIUM CHLORIDE, METHYLPARABEN, HYDROXYPROPYL, METHYLCELLULOSE, CHLORPHENESIN, ALLANTOIN, PARFUM, DIPOTASSIUM GLYCYRRHIZATE, MICA, DISODIUM EDTA, SODIUM HYALURONATE', 64500, 4.5, 'image\\15.png', 5),
(16, 'RISTRA – Acne Spot Drying Trea', 'Ristra Acne Spot Drying Treatment telah teruji secara klinis dapat melawan jerawat secara efektif dan memberikan hasil yang dapat terlihat hanya setelah pemakaian 1 (satu) malam. Acne-spot-treatment yang bekerja cepat dan efektif, diformulasikan secara khusus dengan bahan aktif seperti Calamine, Champor, Salicylic Acid, Sulfur, & Zinc Oxide untuk mengatasi masalah jerawat secara ampuh saat Anda tidur.\r\n\r\nHanya dalam 8 jam: *100% kemerahan pada jerawat berkurang\r\nHanya setelah 3 hari: *73% jumlah jerawat berkurang secara signifikan\r\n\r\n*Berdasarkan studi klinis pada wanita Asia usia 18-46 tahun\r\n', 'Active Ingredients: Salicylic Acid, Calamine, Champor, Sulfur, Zinc Oxide.\r\nFull Ingredients:Ethyl Alcohol, Aqua, Calamine, Zinc Oxide, Titanium Dioxide, Sulfur, Camphor, Talc, Glycerin, Salicylic Acid, Triethoxycaprylylsilane\r\n', 208000, 4.7, 'image\\16.png', 6),
(17, 'I’M FROM – Rice Serum', 'Serum ini mengandung 73% Rice Germ Fermented Extract, yang mempertahankan lebih dari 65% nilai gizi dalam sebutir beras. Diperkaya dengan vitamin B dan antioksidan yang akan meningkatkan produksi kolagen dan meningkatkan elastisitas kulit.\r\n\r\nBeras dengan kualitas terbaik dan premium yang ditanam di Yeoju dimana beras berasal, dan juga disebut sebagai ‘GOA RICE’, memiliki manfaat melembapkan, melembutkan kulit, dan membantu regenerasi sel kulit sehingga keseluruhan kompleksi tampak lebih cerah dan halus. Kaya akan Vitamin B1, B2 dan air beras yang membantu mengencangkan kulit, mempertahankan elastisitas dan mengecilkan tampilan pori. Serta mengandung gammaoryzanol yang bermanfaat untuk mencerahkan, dan bahan aktif yang menjaga kulit tetap lembut sambil mengeksfoliasi sel kulit mati.\r\n\r\nI’m From memilih bahan-bahan berkualitas terbaik dari pertanian lokal di seluruh Korea, misalnya seri Rice yang berasal dari Yeoju, Korea. Beras organik dari Desa Dukpyeng, Yeoju ditanam tanpa pestisida dan menghasilkan beras yang mengandung 3x lebih banyak serat dibanding beras biasa, serta terlihat lebih putih daripada beras biasa.\r\n', 'Aspergillus/Rice Germ Ferment Extract Filtrate, Propanediol, Glycerin, Methylpropanediol, Cyclopentasiloxane, Niacinamide, Caprylyl Methicone , Water (Aqua), Cyclohexasiloxane, 1,2-Hexanediol,Squalane, Betaine, C12-14 Pareth-12, Ammonium Acryloyldimethyltaurate/Vp Copolymer, Panthenol,C30-45 Alkyl Cetearyl Dimethicone Crosspolymer, Ethylhexylglycerin, Allantoin, Xanthan Gum, Dipotassium Glycyrrhizate, Adenosine, Disodium Edta, Pentylene Glycol, Hydrolyzed Hyaluronic Acid, Alpha-Glucan Oligosaccharide, Sodium Hyaluronate, Madecassoside, Portulaca Oleracea Extract, Hydroxypropyl Cyclodextrin, Glutathione', 350100, 4.4, 'image\\17.png', 7),
(18, 'MISSHA – Time Revolution The F', 'The First Essence 5x untuk kulit kendur, kering, kusam dan penuaan dini.\r\n97% Extreme Cica Yeast Ferment™ ditemukan di kondisi ekstrim.  Mengandung ekstrak fermentasi ragi dengan daya hidup tinggi – yang bertahan bahkan di  kondisi ekstrim, yang baik untuk mengantarkan kelembaban padat pada kulit, membantu  menjaga keseimbangan kulit dan menawarkan perawatan dasar untuk kekuatan kulit.\r\n\r\nMenggunakan teknologi baru : Diproses dengan metode PRO FERMENT α ™, Teknologi penyerapan fermentasi dari MISSHA  Teknologi Penyerapan Fermentasi dari MISSHA untuk meningkatkan keramahan pada kulit dan membantu penyerapan,  dengan mengubah kandungan skincare yang efektif yang didapat dari fermentasi ekstrim menjadi  phospholipids yang mirip dengan sktruktur kulit.\r\n\r\nMelalui 3 Proses Fermentasi Spesial yang dilakukan 3 kali di kondisi ekstrim , dingin ,dan hangat.\r\n', 'Key Ingredient FTE 5x :\r\nEnzim cica yang difermentasikan (Ragi) Extract: campuran dari flavonoids, gula, vitamin, dan amino acids yang mengandung antioxidant dalam konsentrasi tinggi untuk menyeimbangkan dan melembabkan kulit kering, rona wajah yang tidak merata atau kulit kusam, memperhalus garis wajah dan memperhalus garis-garis tanda penuaan\r\nNiacinamide: Dikenal dari kegunaannya untuk mencerahkan dan memperhalus kulit, membantu kulit terlihat dan terasa lebih sehat, mengembalikan sistem natural kulit, dan menstimulasi produksi kolagen untuk kulit yang lebih halus dan padat\r\nCeramide NP dan Glycerin: Dua kandungan yang bekerja bersama untuk melembabkan kulit dan mendukung proteksi lapisan pelindung kelembaban kulit.\r\n', 474720, 4.5, 'image\\18.png', 8),
(19, 'Whitelab Sanrio Brightening Fa', 'Whitelab Intense Brightening Serum dengan kandungan Niacinamide 10%, HyaluComplex-10, dan Marine Collagen bekerja sinergis mencerahkan dan menutrisi kulit membuat wajah tampak lebih cerah, lembab dan glowing alami.', '- Niacinamide 10% bekerja maksimal dalam mencerahkan kulit, menyamarkan noda gelap, hiperpigmentasi dan bekas jerawat serta menyamarkan garis halus dan kerutan.\r\n- HyaluComplex-10 yang terdiri dari 10 jenis molekul Hyaluron “low to middle weight molecule” dapat berpenetrasi secara bersamaan pada lapisan kulit yang berbeda dan membentuk moisture barrier sehingga menjaga kelembaban wajah sepanjang hari.\r\n- Marine Collagen yang lebih mudah berpenetrasi ke dalam kulit membantu merawat kehalusan dan kelembutan kulit serta membantu merawat kekenyalan kulit.\r\nIntense Brightening Serum ini cocok untuk kulit yang kusam, banyak noda hitam dan hiperpigmentasi, kulit stress yang ditandai dengan pori-pori terbuka dan kemerahan.\r\n', 79800, 4.8, 'image\\21.png', 4),
(20, 'CETAPHIL - Daily Facial Moistu', 'Moisturizer atau pelembap juga merupakan produk penting yang harus libatkan dalam rutinitas perawatan wajah. Cetaphil Daily Facial Moisturizer SPF 15 PA++ sebagai pelembap yang tidak mengiritasi kulit, formulanya mampu bekerja dengan baik untuk melembapkan dan terasa ringan. Produk ini di klaim cocok untuk semua jenis kulit bahkan untuk kulit sensitif sekalipun.\r\nKeunggulan dari produk ini adalah Lotion ringan yang mampu memperbaiki barrier kulit sekaligus melindunginya dari efek buruk sinar UV, Pemakaian secara teratur dapat mencegah penuaan dini, kulit belang dan kondisi kulit lain akibat paparan sinar UV, Tidak menyumbat pori, Fragrance free, PABA free, non-comedogenic, non-greasy.\r\n', 'Aqua, Octocrylene, Diisopropyl Adipate, Cyclopentasiloxane, Glycerin, Butyl Methoxydibenzoylmethane, Glyceryl Stearate, PEG-100 Stearate, Polymethyl Methacrylate, Phenoxyethanol, Benzyl Alcohol, Triethanolamine, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Tocopheryl Acetate, Carbomer, Disodium EDTA, Cyclotetrasiloxane', 271700, 4.1, 'image\\22.png', 4),
(21, 'AHC - Luminous Glow Real Eye C', 'AHC 8-in-1 Luminous Glow Real Eye Cream for Face diformulasikan dengan Gluta-i™ Complex yang terbukti secara klinis dapat membantu kulit agar terlihat lebih cerah dan awet muda dalam 14 hari.\r\n\r\nDengan 8 manfaat yang telah teruji secara klinis dalam 14 hari dapat membantu:\r\n- Mengembalikan kelembaban kulit\r\n- Menghaluskan garis halus\r\n- Mencerahkan kulit\r\n- Memperbaiki tekstur kulit\r\n- Mengembalikan elastisitas kulit\r\n- Mengencangkan kulit\r\n- Menyamarkan noda hitam\r\n\r\nKrim ini juga dilengkapi dengan Micro Capsule Technology yang telah dipatenkan yang membuat partikel-partikel krim menjadi sangat kecil sehingga dapat terserap hingga lapisan kulit terdalam dan memberikan hasil yang optimal.\r\n', 'Water, Glycerin, Methylpropanediol, Squalane, 1,2-hexanediol, Cyclopentasiloxane, Cyclohexasiloxane, Titanium dioxide, Coco-caprylate/caprate, Panthenol, Bisabolol, Ammonium acryloyldimethyltaurate/vp copolymer, Dimethiconol, Polyhydroxystearic acid, Ethylhexylglycerin, Propanediol, Fragrance, Adenosine, Alumina, Triethoxycaprylylsilane, Disodium edta, Xanthan gum, Polyquaternium-51, Hydrogenated lecithin, Camellia sinensis leaf water, Beta-glucan, Cynara scolymus (artichoke) leaf extract, Pteris multifida extract, Avena sativa (oat) kernel extract, Tromethamine, Carbomer, Polysorbate 20, Acmella oleracea extract, Niacinamide, Raffinose, Pentylene glycol, Cholesterol, 3-o-ethyl ascorbic acid, Sodium hyaluronate, Ascorbic acid, Tocopherol, Linolenic acid, Ceramide np, Glutathione, Saccharide hydrolysate, Maltodextrin, Ascorbic acid polypeptide, Ascorbyl glucoside, Zinc pca, Olea europaea (olive) leaf extract', 149500, 4.6, 'image\\23.png', 4),
(22, 'TULUS - Balanced Gel Cleanser', 'Kulit sehat dimulai dari cara membersihkan yang benar. Sabun pembersih wajah ini memiliki kandungan ph yang seimbang, tidak mengikis saat membersihkan riasan wajah, kotoran, dan minyak untuk hasil wajah yang berseri dan cerah. Bunga Kamomil, Kacang Almond, dan Oat Kernel bekerja sama dengan pelembab lainnya untuk menghidrasi dan menyegarkan kulit sembari membersihkan kotoran yang menyumbat pori-pori tanpa mengurangi kelembaban kulit.', 'Water, Glycerin, Coco-Betaine, Xanthan Gum, Sodium Chloride, Coco-Glucoside, Glyceryl Caprylate, Caprylyl Glycol, Decyl Glucoside, Betaine, Butylene Glycol, Sodium Cocoyl Isethionate, Disodium EDTA, Panthenol, 1,2-Hexanediol, Anthemis Nobilis Flower Extract, Citric Acid, Quillaja Saponaria Bark Extract, Allantoin, Caffeine, Camellia Sinensis Leaf Extract, Sodium PCA, Propylene Glycol, Avena Sativa (Oat) Kernel Extract, Phenoxyethanol, Prunus Amygdalus Dulcis (Sweet Almond) Seed Extract, Ethylhexylglycerin.', 159000, 4.8, 'image\\24.png', 4),
(23, 'SUKIN - Oil Balancing Purifyin', 'Sukin Oil Balancing Purifying Gel Cleanser\r\n•Gel cleanser\r\n•Untuk kulit berminyak dan kombinasi\r\n•Tanpa sulphate, silicone\r\n•Menyeimbangkan kadar minyak\r\n•Membersihkan pori-pori dari polusi dan kotoran tanpa menghilangkan minyak alami kulit\r\n', 'Water (Aqua), Aloe Barbadensis Leaf Juice, Cocamidopropyl Betaine, Decyl Glucoside, PEG-150 Pentaerythrityl Tetrastearate, Glycerin, Charcoal Powder (Bamboo Charcoal), Chamomilla Recutita (Matricaria) Flower Extract (Chamomile), Aspalathus Linearis Leaf Extract (Rooibos), Epilobium Angustifolium Extract (Willowherb), Vaccinium Myrtillus Fruit Extract (Bilberry), Punica Granatum Fruit Extract (Pomegranate), Cucumis Sativus (Cucumber) Fruit Extract, Cocos Nucifera (Coconut) Fruit Extract, Moringa Oleifera Leaf Extract, Citrus Nobilis (Mandarin Orange) Peel Oil, Lavandula Angustifolia (Lavender) Oil, Citrus Aurantifolia (Lime) Oil, Citrus Aurantium Amara (Bitter Orange) Leaf/Twig Oil (Petitgrain), Backhousia Citriodora Leaf Oil (Lemon Myrtle), Phenoxyethanol, Benzyl Alcohol, Limonene, Linalool. * Natural component of essential oil', 179000, 4.5, 'image\\25.png', 8),
(24, 'EVERWHITE - Strawberry Clay Ma', 'Masker Wajah dengan kandungan utama BENTONITE CLAY & STRAWBERRY.', '-', 108900, 4.4, 'image\\26.png', 8),
(25, 'AZARINE - CBD Hydraoxidant Amp', 'Ampoule ringan yang diformulasikan dengan berbagai bahan aktif alami antioksidan kulit. Selain itu juga membantu menjaga kesehatan garis pertahanan kulit (skin barrier) agar kulit terlindungi dari radikal bebas. Ampoule ini juga mengandung multivitamin agar kulit halus dan lembut', 'Aqua, Glycerin, Propanediol, Niacinamide, Methyl Cyclodextrin, Pichia/Resveratrol Ferment Extract, Sodium Hyaluronate, Centella Asiatica Extract, Ceramide 3, Xanthan Gum, Glycolic Acid, 7-Dehydrocholesterol, Ascorbic Acid, Tocopheryl Acetate, Retinyl Palmitate, Brassica Campestris Sprout Extract, Brassica Oleracea Italica Sprout Extract, Brassica Oleracea Gemmifera Extract, Sunflower (Helianthus Annuus) Seed Oil, Arctium Lappa Root Extract, Chlorphenesin, Phenoxyethanol, Panthenol, Portulaca Oleracea Extract*.', 131750, 4.7, 'image\\27.png', 3),
(26, 'WHITELAB - Granactive retinoid', 'Dengan kandungan utama Granactive Retinoid 1% + Peptide + Beta Glucan\r\nWhitelab Intensive Care Serum menggunakan Granactive Retinoid 1% yang merupakan Advanced Retinoid generasi terbaru, yang memberikan manfaat serupa dengan Retinol namun minim iritasi dan efektif diaplikasikan setiap hari.\r\n\r\nOleh karena itu, Whitelab Intensive Care serum sangat cocok digunakan untuk membantu mengurangi masalah tanda tanda penuaan, noda pada kulit serta problem wajah yang kusam.\r\n', '-Granactive Retinoid 1% dapat membantu menyamarkan tanda tanda penuaan pada kulit, seperti kerutan dan garis halus pada wajah, serta dapat membantu menyamarkan noda bekas jerawat.\r\n-Peptide bermanfaat untuk membantu meningkatkan elastisitas serta kekencangan pada kulit.\r\n-Beta Glucan bermanfaat untuk membantu memperkuat fungsi pertahanan kulit, serta merawat kehalusan dan mencerahkan wajah.\r\n', 99900, 4.7, 'image\\28.png', 3),
(27, 'BREYLEE - Serum Mata Roll On R', 'Mengandung Vitamin A (Retinol) dan bermacam- macam ektrak tumbuhan. Melembabkan, men- gencangkan, dan membantu memperbaiki kulit. Efektif untuk menyamarkan garis- garis halus, kerutan, dan kantong mata, melembutkan serta mengencangkan kulit area mata dan membantu mencerahkan area mata akibat lingkaran hitam dan kantong mata.', 'Aqua, Glycerin, Cyclopentasiloxane, Ethylhexylglycerin, 1,2-Hexanediol, Scutellaria Baicalensis Root Extract, Betaine, Cyclohexasiloxane, Sophora Angustifolia Root Extract, Tocopherol, Dimethicone, Triethoxycaprylylsilane, Panthenol, Phenoxyethanol, Ethylhexyl Palmitate, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Isononyl Isononanoate, Titanium Dioxide, Hyaluronic Acid, Hydrogenated Polyisobutene, Carbomer, Triethanolamine ,Xanthan Gum, Methylparaben, Synthetic Fluorphlogopite', 48000, 4.4, 'image\\29.png', 5),
(28, 'DEAR ME BEAUTY - 2% Salicylic ', 'Serum dengan kandungan 2% Salicylic Acid (BHA) dan ekstrak buah lemon yang berasal dari New Jersey, USA. Telah diformulasikan khusus untuk membersihkan sel-sel kulit mati hingga ke dalam pori, mengurangi kemerahan, dan mengatasi kulit berjerawat.\r\nSerum 2% Salicylic Acid (BHA) dan ekstrak buah lemon ini diformulasikan dengan menggunakan Salsphere Technology di mana salicylic acid di mikroenkapsulasi yang dapat membuatnya lebih mudah menembus ke lapisan kulit lebih dalam\r\n', 'Water, PEG-8, Salicylic Acid, Propanediol, Propylene Glycol, Triethanolamine, Aloe Barbandesis (Leaf) Extract, Citrus Limonum (Lemon) Fruit Extract, Phenoxyethanol, Glycerin, Isostearamidopropyl Ethyldimonium Ethosulfate, Sodium Hydroxide, Ethylhexylglycerin, Citric Acid, Sodium Citrate, Soluble Collagen, Xanthan Gum, Isopropyl Methylphenol, Maclura Cochinchinensis Leaf Prenylflavonoids, Panthenol, Sodium Benzoate, Potassium Sorbate, Carthamus Tinctorius Seed Oil, Olea Europea (Olive) Fruit Oil.', 69300, 4.7, 'image\\30.png', 6),
(29, 'COSRX - Refresh AHA/BHA Vitami', 'Toner yang ringan dan cocok untuk semua jenis kulit. Dengan kandungan Actinidia Chinensis dan hylocereus undatus pada GOLDEN-RX COMPLEX™ formula yang dapat membantu menghaluskan dan mencerahkan kulit.', 'Actinidia Chinensis (Kiwi) Fruit Extract, Hylocereus Undatus Fruit Extract, Salix Alba (Willow) Bark Water, Pyrus Malus (Apple) Fruit Water, Butylene Glycol, Niacinamide, 1,2-Hexanediol, Ethyl Hexanediol, Sodium Lactate, Water, Glycolic Acid, Allantoin, Panthenol, Adenosine, Betaine Salicylate, Ascorbyl Glucoside', 183200, 4.6, 'image\\31.png', 6),
(30, 'AVOSKIN - Perfect Hydrating Tr', 'Essence ini berfungsi untuk menjaga kesegaran dan kelembaban kulit. Diperkaya dengan asam askorbat / ETVC, ekstrak chamomile, minyak wortel, dan minyak rosehip, rasakan sensasi menenangkan yang dapat membuat kulit terasa lebih lembut dan kenyal, cerah alami, dengan pori-pori wajah yang semakin mengecil dari hari ke hari dengan pemakaian yang rutin.', 'Aqua, Alcohol, Ethyl Ascorbic Acid, Propylene Glycol, Glycerin, Fragrance, Chamomile (Anthemis Nobilis) Extract, Carrot (Carota Sativa) Oil, Rosa Canina (Rosehip) Oil, Carbomer, Triethanolamine, Mineral Oil', 165400, 4.5, 'image\\32.png', 7),
(31, 'BREYLEE - Step 1 Blackhead Rem', 'Mengangkat komedo, kotoran, dan minyak berlebih', 'Aqua / Air, Minyak Daun Melaleuca Alternifolia (Pohon Teh), Ekstrak Daun Aloe Barbadensis, Glycerin, Royal Jelly', 59200, 4.6, 'image\\33.png', 4),
(32, 'LOREAL PARIS - Revitalift Crys', 'REVOLUSI PERAWATAN KULIT TERBARU DARI L’OREAL PARIS.\r\n\r\nL\'OREAL PARIS REVITALIFT CRYSTAL MICRO ESSENCE.\r\nEssence terbaru dari L’Oreal Paris untuk kulit tampak sebening kristal. Dengan Micronized Technology dapat menyerap hingga 10 lapisan* dalam tekstur ringan dan terobosan baru yang lebih cair, melembabkan dan cepat menyerap.\r\nBahan Aktif Pencerah Kulit, mempercepat proses pembaruan kulit, menyamarkan tampakan pori, dan menghaluskan tekstur kulit.\r\nCentella Asiatica, bekerja dari dalam, menyamarkan garis halus untuk kulit yang lebih halus dan tampak muda.\r\n', '-', 301800, 4.6, 'image\\34.png', 4),
(33, 'SCARLETT WHITENING - Scarlett ', 'Scarlett Herbalism Mugwort Mask dapat digunakan untuk merawat kulit berminyak, pori-pori besar, berjerawat dan berkomedo. ', 'Mugwort Extract, Vitamin C, Glutathione, Niacinamide, Bamboo Charcoal, Allantoin, Chlorophyllin, Green Tea Powder', 74250, 4.5, 'image\\35.png', 4),
(34, 'ROJUKISS - Orange C+ Bright Po', 'Serum perawatan wajah untuk kulit kusam dan pori-pori membesar. Diperkaya ekstrak Jeruk, Vitamin C, Vitamin E, dan Witch Hazel.\r\n\r\nMembantu menutrisi dengan efektif, mencerahkan, dan mengencangkan pori, sehingga kulit tampak lebih cerah, berseri, halus dan mulus.\r\n', 'Water, Dipropylene Glycol, Butylene Glycol, Niacinamide, 1,2-Hexanediol, Hamamelis Virginiana (Witch Hazel) Extract, PPG-26-Buteth-26, PEG-40 Hydrogenated Castor Oil, Ethylhexylglycerin, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Chondrus Crispus Extract, Allantoin Tromethamine, Saccharum Officinarum (Sugarcane) Extract), Fragrance (Parfum), Zea Mays (Corn) Stratch , Microcrystalline Cellulose, Mannitol, Disodium EDTA, Sucrose, Glutathione, Tacopheryl Acetate, Phenoxyethanol, Titanium Dioxide (Cl 77891), Iron Oxids (Cl 77491), Tocopherol, Ascorbic Acid, Iron Oxides (Cl 77492), Salix Nigra (Willow) Bank Extract, Citrullus Lanatus (Watermelon) Fruit Extract, Solanum Armeniaca (Apricot) Fruit Extract , Citrus Aurantium Dulcis (Orange) Fruit Extract, Citrus Paradisi (Grapefruit) Fruit Extract, Carica Papaya (Papaya) Fruit Extract', 90300, 4.7, 'image\\36.png', 4),
(35, 'QV SKINCARE - QV Skin Lotion', 'Membantu memperbaiki kulit kering', 'Aqua, Glycerin, Petrolatum, C12-15 Alkyl Benzoate, Cetearyl Alcohol,Cteareth-20, Steareth-2, Dimethico, Glyceril Stearate,Methylparaben,Propylparaben, Dichlorobenzyl Alcohol, Polyacrilic Acid, Triethanolamie', 186400, 4.8, 'image\\37.png', 1),
(36, 'NPURE - Cica Beat The Sun SPF ', 'Natural daily sun protection with SPF 50 PA ++++ that is formulated with 100% Natural Cica Leaf Water, Chrysanthemum Extract, Chamomile Extract, and Camellia Sinensis Leaf Extract. This sun cream contains 5 types of UV filter that protects skin against UVA & UVB rays while moisturizing and soothing the skin.', 'Natural Cica Leaf Water, Ekstrak Chrysanthemum, Ekstrak Chamomile, dan Ekstrak Daun Camellia', 107100, 4.9, 'image\\38.png', 1),
(37, 'DHC - Deep Cleansing Oil', 'Pembersih wajah yang terbuat dari olive oil alami yang dapat membersihkan dan melembutkan tanpa membuat kulit terasa berminyak. Dapat membersihkan kotoran dan make-up bahkan waterproof maskara & eyeliner sekalipun.', 'olea europaea (olive) fruit oil, caprylic/capric triglyceride, sorbeth-30 tetraoleate, pentylene glycol, phenoxyethanol, tocopherol, stearyl glycyrrhetinate, rosmarinus officinalis (rosemary) leaf oil', 284000, 4.5, 'image\\39.png', 1),
(38, 'NPURE - Cica Acne Spot', 'Cica Acne Spot dengan Granactive Acne Peptide (Peptide, Oryza Sativa (Rice) Bran Extract, Boswellia Serrata Resin Extract, dan Honey Extract) berfungsi melawan bakteri penyebab jerawat (P.acnes) pada kulit tanpa menyebabkan iritasi. Diperkuat dengan Salicylic Acid dan Sulfur sebagai acne treatment rekomendasi FDA untuk mengatasi jerawat. Kandungan Centella Asiatica Extract pada Cica Acne Spot memberikan efek menenangkan dan dapat mengurangi kulit kemerahan. Selain itu, diperkaya dengan Zinc PCA, Niacinamide, dan Calamine yang membantu membersihkan pori-pori dari kotoran dan mengurangi minyak berlebih. Cica Acne Spot cocok untuk semua jenis kulit.', 'Centella Asiatica Extract\r\nGranactive Acne Peptide (Oligopeptide-10, Oryza Sativa Bran Extract, Boswellia Serrata Extract, Honey Extract)\r\nSalicylic Acid\r\nSulfur\r\nCalamine (Zinc Carbonate & Iron Oxide/CI 77499)\r\nZinc PCA\r\nNiacinamide\r\nMilk Protein\r\n', 69000, 4.7, 'image\\40.png', 8);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `concern`
--
ALTER TABLE `concern`
  ADD PRIMARY KEY (`id_concern`);

--
-- Indexes for table `skincare`
--
ALTER TABLE `skincare`
  ADD PRIMARY KEY (`id_skincare`),
  ADD KEY `skkincare_concern` (`id_concern`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `concern`
--
ALTER TABLE `concern`
  MODIFY `id_concern` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=39;

--
-- AUTO_INCREMENT for table `skincare`
--
ALTER TABLE `skincare`
  MODIFY `id_skincare` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=39;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `skincare`
--
ALTER TABLE `skincare`
  ADD CONSTRAINT `skkincare_concern` FOREIGN KEY (`id_concern`) REFERENCES `concern` (`id_concern`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
